[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[general]
live_config_reload = true

[window]
padding = { x = 8, y = 8 }
decorations = "Full"
opacity = 1.0
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

[terminal]
osc52 = "CopyPaste"

